import { NextPageContext } from 'next';
import Head from 'next/head';
import Link from 'next/link';

export default function IndexPage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-10">
        <Link
          className="p-6 max-w-sm bg-lime-300 rounded-xl shadow-lg flex items-center space-x-4 mx-9 mb-5"
          href="/dashboard"
        >
          대시보드
        </Link>
        <Link
          className="p-6 max-w-sm bg-lime-300 rounded-xl shadow-lg flex items-center space-x-4 mx-9"
          href="/record"
        >
          기록표
        </Link>
      </main>
    </div>
  );
}

export async function getServerSideProps({ query }: NextPageContext) {
  const props = {
    title: 'test',
  };
  return {
    props,
  };
}
