import { NextPageContext } from "next";
import Head from "next/head";
import Link from "next/link";

export default function IndexPage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        나의 헬스 기록표
        <Link
          className="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-lg flex items-center space-x-4"
          href="/dashboard"
        >
          대시보드
        </Link>
        <Link
          className="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-lg flex items-center space-x-4"
          href="/record"
        >
          기록표
        </Link>
      </main>
    </div>
  );
}

export async function getServerSideProps({ query }: NextPageContext) {
  const props = {
    title: "test",
  };
  return {
    props,
  };
}
